---
# Built documents output path.
# ../Build means Build directory on Source document root's parent directory.
outdir: ../Build
#outdir: /home/foo/public_html/
# Loading CSS files (userd by Pandoc's default template.)
# This values must be *server's URL*.
css:
  - /css/layout.css
  - /css/base.css
# Enable TOC. true or false. false by default.
toc: true
# Enable eRuby template expansion. true or false. false by default.
post_eruby: false
# Pandoc's default file settings.
# It is merge into default file. See https://pandoc.org/MANUAL.html#default-files
pandoc_additional_options:
  metadata:
    lang: ja
    title-prefix: "Powered by PureBuilder Simply"
#  include-before-body:
#    - before.html
#  include-after-body:
#    - after.html
#
# Default metadata. If same key exists in document's frontmatter, document's frontmatter is given priority to this settings.
default_meta:
  author: "John Doe"
# Override every ACCS index page's frontmatter.
alt_frontmatter:
  title: Serial documents by ACCS
# Testserver (pbsimply-testserver.rb)'s port. 8000 by default.
#testserver_port: 8000
# Generated document's URL absolute prefix. This value replaces reading /.
#self_url_prefix: /foowebsite/
# Generated document's URL absolute prefix. This value replaces reading /. Used by page_url_encoded_external.
self_url_external_prefix: https://example.com/
# Database format. use JSON if set json or oj.
#dbstyle: json
# Blessing way. If cmd given, you external command instead of Ruby function.
#bless_style: cmd
# Blessing external command
#bless_cmd: [echo, BLESS]
# Blessing external command on ACCS.
#bless_accscmd: [echo, ACCS]